In [1]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img=mpimg.imread('D:/FaraDars.org/T1059/MACHINELEARN/6/code_6/Neurons.png')
a = plt.imshow(img)
a;

In [2]:
'''
HOURS STUDIED     HOURS SLEPT        	        TEST SCORE 
    2                  9	                         92
    1                  5	                         86
    3                  6	                         89
    5                  10	                         ?


 (2 * .2) + (9 * .8) = 7.6      S(7.6) = 0.999499799
 (2 * .6) + (9 * .3) = 3.9      S(7.5) = 1.000553084
 (2 * .1) + (9 * .7) = 6.5      S(6.5) = 0.998498818


(.9994 * .4) + (1.000 * .5) + (.9984 * .9) = 1.79832     S(1.79832) = .8579443067
'''

'\nHOURS STUDIED     HOURS SLEPT        \t        TEST SCORE \n    2                  9\t                         92\n    1                  5\t                         86\n    3                  6\t                         89\n    5                  10\t                         ?\n\n\n (2 * .2) + (9 * .8) = 7.6      S(7.6) = 0.999499799\n (2 * .6) + (9 * .3) = 3.9      S(7.5) = 1.000553084\n (2 * .1) + (9 * .7) = 6.5      S(6.5) = 0.998498818\n\n\n(.9994 * .4) + (1.000 * .5) + (.9984 * .9) = 1.79832     S(1.79832) = .8579443067\n'

In [3]:
import numpy as np

In [4]:
xAll = np.array(([2, 9], [1, 5], [3, 6], [5, 10]), dtype=float)   #(hours studying, hours sleeping)
xAll

array([[ 2.,  9.],
       [ 1.,  5.],
       [ 3.,  6.],
       [ 5., 10.]])

In [5]:
# scaling input data
xAll = xAll/np.amax(xAll, axis=0)   
xAll

array([[0.4, 0.9],
       [0.2, 0.5],
       [0.6, 0.6],
       [1. , 1. ]])

In [6]:
y = np.array(([92], [86], [89]), dtype=float)   # y = score on test
y

array([[92.],
       [86.],
       [89.]])

In [7]:
# scaling output data (max test score is 100)
y = y/100      
y

array([[0.92],
       [0.86],
       [0.89]])

In [8]:
# training data
X = np.split(xAll, [3])[0]           
X

array([[0.4, 0.9],
       [0.2, 0.5],
       [0.6, 0.6]])

In [9]:
xtest = np.split(xAll, [3])[1]   # testing data
xtest

array([[1., 1.]])

In [10]:
class Neural_Network(object):
    def __init__(self):
        self.inputSize  = 2
        self.outputSize = 1
        self.hiddenSize = 3
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize)    # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)   #(3x1) weight matrix from hidden to output layer

    #forward propagation 
    def forward(self, X):
      self.z  = np.dot(X, self.W1)          # dot product of X (input) and first set of 3x2 weights
      self.z2 = self.sigmoid(self.z)        # activation function
      self.z3 = np.dot(self.z2, self.W2)    # dot product of hidden layer (z2) and second set of 3x1 weights
      o = self.sigmoid(self.z3)             # final activation function
      return o

    # activation function
    def sigmoid(self, s):
      return 1/(1+np.exp(-s))

In [11]:
NN = Neural_Network()

In [12]:
o = NN.forward(X)    
o

array([[0.52933586],
       [0.52858312],
       [0.52640196]])

In [13]:
y

array([[0.92],
       [0.86],
       [0.89]])

In [14]:
# Backward Propagate

In [15]:
def sigmoidPrime(self, s):
    return s * (1 - s)

def backward(self, X, y, o):
    self.o_error = y - o                                     # error in output
    self.o_delta = self.o_error*self.sigmoidPrime(o)         # applying derivative of sigmoid to error

    self.z2_error = self.o_delta.dot(self.W2.T)   # z2 error: how much our hidden layer weights contributed to output error
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

    self.W1 += X.T.dot(self.z2_delta)                        # adjusting first set (input --> hidden) weights
    self.W2 += self.z2.T.dot(self.o_delta)                   # adjusting second set (hidden --> output) weights

In [16]:
def train(self, X, y):
    o = self.forward(X)
    self.backward(X, y, o)

In [17]:
def saveWeights(self):
    np.savetxt("w1.txt", self.W1, fmt="%s")
    np.savetxt("w2.txt", self.W2, fmt="%s")

In [18]:
def predict(self):
    print( "Predicted data based on trained weights: ");
    print( "Input (scaled): \n" + str(xPredicted));
    print( "Output: \n" + str(self.forward(xPredicted)));

In [19]:
NN = Neural_Network()

In [20]:
def think(self, inputs):
    #pass inputs through our single neuron(our single neuron)
    return self.___sigmoid(dot(inputs, self.synaptic_weights))

In [21]:
for i in range(3):                          
  print ("iteration:" + str(i) )
  k=np.mean(np.square(y - NN.forward(X)))    # mean sum squared loss
  print ("Loss: " + str(k))       
  print ("\n")
  NN.train(X, y)

iteration:0
Loss: 0.015811222854921658




AttributeError: 'Neural_Network' object has no attribute 'train'